# Generated by Django 2.2 on 2022-04-23 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='categories',
        ),
    ]
