# Generated by Django 2.2 on 2022-04-23 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_shop_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shop_id',
            field=models.IntegerField(default=1),
        ),
    ]
