# Generated by Django 2.2 on 2022-04-23 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_shop_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shop_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='api.Shop'),
        ),
    ]
