# Generated by Django 2.2 on 2022-04-28 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='products',
            new_name='prod',
        ),
        migrations.RemoveField(
            model_name='order',
            name='comfortable_time',
        ),
    ]
